spring:
  datasource:
#    url: jdbc:mysql://secapstoneproject.mysql.database.azure.com:3306/cloud_vendor?useSSL=false
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: adebayor9
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  #JPA Setting
#  jpa:
#    hibernate:
#      ddl-auto: create
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "caches"
      base-path: "/management-dashboard"
  endpoint:
    health:
      show-details: always

dummyService:
  port: 8081
  address: 127.0.0.1